
[build]
  publish = "public"
  functions = "functions"
[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "Content-Type"
Access-Control-Allow-Methods = "GET,POST,PUT,DELETE,OPTION"
